
INSERT INTO state (name, country_id) VALUES
('Zachodniopomorskie',1),
('Pomorskie',1),
('Warmińsko-mazurskie',1),
('Podlaskie',1),
('Lubuskie',1),
('Wielkopolskie',1),
('Kujawsko-pomorskie',1),
('Mazowieckie',1),
('Lubelskie',1),
('Podkarpackie',1),
('Świętokrzyskie',1),
('Małopolskie',1),
('Śląskie',1),
('Łódzkie',1),
('Opolskie',1),
('Dolnośląskie',1),
('Alberta',2),
('British Columbia',2),
('Manitoba',2),
('New Brunswick',2),
('Newfoundland and Labrador',2),
('Northwest Territories',2),
('Nova Scotia',2),
('Nunavut',2),
('Ontario',2),
('Prince Edward Island',2),
('Quebec',2),
('Saskatchewan',2),
('Yukon',2),
('Baden-Württemberg',3),
('Bavaria',3),
('Berlin',3),
('Brandenburg',3),
('Bremen',3),
('Hamburg',3),
('Hesse',3),
('Lower Saxony',3),
('Mecklenburg-Vorpommern',3),
('North Rhine-Westphalia',3),
('Rhineland-Palatinate',3),
('Saarland',3),
('Saxony',3),
('Saxony-Anhalt',3),
('Schleswig-Holstein',3),
('Thuringia',3);