name: Deploy backend with CD

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - backend/**

jobs:
  deploy:
    defaults:
      run:
        working-directory: ./backend
    runs-on: ubuntu-latest
    steps:
      - uses: mirromutth/mysql-action@v1.1
        with:
          host port: 3306
          container port: 3306
          character set server: 'utf8'
          collation server: 'utf8_general_ci'
          mysql database: 'shop'
          mysql root password: ${{ secrets.RootPasswordTesting }}
          mysql user: 'root'
          mysql password: ${{ secrets.DatabasePasswordTesting }}
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Add build nr
        id: build-number
        run: echo "BUILD_NUMBER=$(date '+%d.%m.%Y.%H.%M.%S')" >> $GITHUB_OUTPUT
      - name: Build and push to Docker Hub
        run: mvn -ntp verify -Ddocker.image.tag=${{ steps.build-number.outputs.BUILD_NUMBER }} jib:build
      - name: Update Dockerrun.aws.json with the new build nr
        run: |
          echo "Dockerrun.aws.json before updating build nr"
          cat Dockerrun.aws.json
          sed -i -E 's_(tomeklfc111/ecommerce-shop:)([^"]*)_\1'${BUILD_NUMBER}'_' Dockerrun.aws.json
          echo "Dockerrun.aws.json after updating build nr"
          cat Dockerrun.aws.json
          - name: Deploy to EB
      - uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ secrets.EB_APPLICATION_NAME }}
          environment_name: ${{ secrets.EB_ENVIRONMENT_NAME }}
          version_label: ${{ steps.build-number.outputs.BUILD_NUMBER }}
          region: ${{ secrets.EB_REGION }}
          deployment_package: backend/Dockerrun.aws.json
          version_description: ${{ github.SHA }}
      - name: Commit, push new Dockerrun.aws.json
        run: |
          git config user.name github-actions
          git config user.email github-actions@example.com
          git add .
          git commit -m "update Dockerrun.aws.json with new tag ${{ steps.build-number.outputs.BUILD_NUMBER }}"
          git push
